### ISSUE TITLE
Raspberry Pi i2c support

### ISSUE THREAD

**Issue by LonerDan** [barebox/barebox#10]
I am using barebox as flexible bootloader on Raspberry Pi 3B+. I am very happy with the experience so far, but one feature that would be useful for my use case is access to the i2c bus. Is there any particular reason there is no driver for it in barebox or is it just that nobody got around to port it yet?

**Comment by frantony** [comment]
@LonerDan 

There is the I2C_GPIO bitbang driver in barebox.

Could you use it on top of existing barebox rpi gpio driver?

**Comment by LonerDan** [comment]
@frantony 
Thank you. Although not ideal, I will have a look and try it. However, the focus of my question was mainly to determine if there is any platform-specific obstacle (Broadcom firmware for example) in porting the native i2c driver from Raspberry Pi´s kernel or if simply nobody had time to do so.

**Comment by a3f** [comment]
@LonerDan Like most missing drivers, it's likely that no one came around to do it. If you need it, you're encouraged to send a patch. You might find it easier to port the driver from U-Boot than from the kernel, because U-Boot already does it in poll-mode instead of relying on interrupts (which aren't used in barebox).

**Comment by LonerDan** [comment]
Thank you for the tips. I was busy with other projects and in the end decided to use the I2C GPIO drivers with the pins normally used by I2C (GPIO2=SDA, GPIO3=SCL). My setup is on Raspberry PI 3 B+ with AT24C256 EEPROM and DS1307 RTC, both working fine using the existing drivers.

**Comment by LonerDan** [comment]
If anybody else stumbles upon this, there is now support for the bcm283x i2c controller added by 8be7c4f.
