### ISSUE TITLE
bcm2835 framebuffer driver not working on Raspberry PI 3B+

### ISSUE THREAD

**Issue by LonerDan** [barebox/barebox#11]
Hello,
I have Raspberry PI 3B+ with Barebox 2021.07.0 running on it. The bootloader loads fine and I have a working I2C with EEPROM and RTC, but I can't seem to get the display driver working. I use the official Raspberry PI 7" LCD touchscreen connected via DSI. I can see that the driver at least tries to do something since the test pattern generated by the first stage bootloader goes away and the screen goes black with the backlight still on, but neither fbtest nor splash programs seem to do anything.  Driver doesnt throw any errors and devinfo shows the correct resolution of the LCD.
![fb0_devinfo](https://user-images.githubusercontent.com/11718484/129683175-633ea6b2-48f4-418e-8a91-3e15308f27fe.PNG)
Do you have any clue what might be wrong? Did the framebuffer interface change between the SoC versions? Or at least, did somebody had it working on a PI before?
Here is my Barebox build configuration:
[barebox-config.txt](https://github.com/saschahauer/barebox/files/6997900/barebox-config.txt)

**Comment by a3f** [comment]
I haven't used it myself, but what happens if you do `fb0.enable=1 fbtest`?

**Comment by LonerDan** [comment]
I tried that, no change. Looking at the source of the driver, the enable and disable op functions do nothing anyway.

**Comment by LonerDan** [comment]
I looked at the u-boot equivalent driver and they use different pixel format (32-bit RGB, whereas barebox uses 16-bit BGR). So I thought I try to modify barebox to use those values as well, but it seems not to do the trick by itself. The next difference that stands out to me is that they translate the address of the returned frame buffer from bus address to physical address. In what address space does Barebox operate?

**Comment by LonerDan** [comment]
So I managed to find the problem. It was with the returned address which needed to be converted into ARM address space. It's done by shifting it by offset 0xc0000000. Although the property mailbox channel 8 according to [firmware wiki](https://github.com/raspberrypi/firmware/wiki/Accessing-mailboxes) uses addresses inside ARM space, the framebuffer setup [seems to be a exception](https://www.raspberrypi.org/forums/viewtopic.php?t=298084). 
Tested working on Raspberry PI 3B+.

**Comment by LonerDan** [comment]
I also had problems getting booted Linux to use the serial console before I fixed the framebuffer driver. My theory is that it was writing garbage into the peripheral registers since the unconverted address is roughly in that range.

**Comment by LonerDan** [comment]
Ok, so I updated my pull request #12 . As suggested, I used 'of_dma_get_range' to get the VC MMU mapping in a portable way. It also seems that it doesn't matter that on the PI 1 the returned address range is L2 cached as I mentioned previously. I tested the code both on the Raspberry Pi 1B+ (mapping 0x40000000) and Raspberry Pi 3B+ (mapping 0xc0000000) and they work OK.

**Comment by LonerDan** [comment]
An improved fix was posted to the mailing list, so I am closing this here.
