### ISSUE TITLE
arch/arm/dts/imx8mp.dtsi breaks kernel for IMX8MP Lite

### ISSUE THREAD

**Issue by hcl-dr** [barebox/barebox#20]
```
&pgc_mediamix {
	barebox,feature-gates = <&feat IMX8M_FEAT_ISP>;
};
```
Offending line.

This domain is consumed by generic display resources unrelated
to the existence of the ISP. Masking it breaks the IMX8MP Lite.

**Comment by a3f** [comment]
Thanks for the report. Can you send a patch?
