### ISSUE TITLE
error in beaglebone build since v2024.5.0

### ISSUE THREAD

**Issue by CryxosMarco** [barebox/barebox#27]
Hello,

I encountered an issue while trying to build the latest version of Barebox to run on a Beaglebone Black. Here are the steps I followed:

- Cloned the repo.
- Set ARCH to arm and CROSS_COMPILE to my toolchain.
- Ran `make distclean`.
- Ran `make am335x_mlo_defconfig`.
- Ran `make`.

However, the build process fails with the following output:

```
...
 LD      images/start_am33xx_beaglebone_sram.pbl
 OBJCOPYB images/start_am33xx_phytec_phycore_sram_512mb.pblb
 CHKFILESIZE images/start_am33xx_phytec_phycore_sram_512mb.pblb
 OBJCOPYB images/start_am33xx_phytec_phycore_sram_2x512mb.pblb
images/start_am33xx_phytec_phycore_sram_512mb.pblb size 113556 > maximum size 111616
make[1]: *** [/home/marco/Git/barebox/images/Makefile:83: images/start_am33xx_phytec_phycore_sram_512mb.pblb] Error 1
make[1]: *** Deleting file `images/start_am33xx_phytec_phycore_sram_512mb.pblb`
make[1]: *** Waiting for unfinished jobs....
 CHKFILESIZE images/start_am33xx_phytec_phycore_sram_2x512mb.pblb
images/start_am33xx_phytec_phycore_sram_2x512mb.pblb size 113556 > maximum size 111616
make[1]: *** [/home/marco/Git/barebox/images/Makefile:81: images/start_am33xx_phytec_phycore_sram_2x512mb.pblb] Error 1
make[1]: *** Deleting file `images/start_am33xx_phytec_phycore_sram_2x512mb.pblb`
make: *** [Makefile:736: images] Error 2
```

When I checkout to version v2024.04.0 or earlier, the same procedure works fine. I noticed that the line CONFIG_BAREBOX_MAX_IMAGE_SIZE=0xffffffff seems to influence the error message. I tried setting it to 0xffffffff in the latest git version, which allowed me to build the images, but they failed to boot on my Beaglebone Black.

The v2024.04.0 version works without issues.

Let me know if you need further Information.

~ Marco

**Comment by saschahauer** [comment]
Hi,

barebox became too big with the latest NAND layer update. There are a
few patches queued up for master which will be in the upcoming release
which fix this. These are:

eb6429a2b8 mtd: nand: Kconfig: whitespace cleanups
0958c15ceb mtd: nand: make exec_op optional
d1fe68f1b0 mtd: nand: make interleaved placement optional
ec3b8c646b mtd: nand: fix compilation

You can also find them here:

https://lore.barebox.org/barebox/171869122549.3822978.7856249240200139957.b4-ty@pengutronix.de/T/#t

(Note the last one is a fixup which is not on the list)

**Comment by a3f** [comment]
All of these are in [v2024.07.0](https://github.com/barebox/barebox/releases/tag/v2024.07.0), which should fix your issue. If not, please reopen.
