### ISSUE TITLE
uimage verify  of nfs mounted image produced different CRC each time

### ISSUE THREAD

**Issue by Rashidwi** [barebox/barebox#28]
version:
barebox 2022.02.0-bsp-yocto-i.mx6ul-pd19.1.1 #1 Fri Sep 1 14:00:23 UTC 2023

I'm unable to nfs boot my image as it fails with a crc error.

 

> Booting entry 'myapp (/mnt/nfs-192.168.1.1-bootentries-000053dc/loader/entries/erlang.conf)'
>  blspec: booting myapp from none
>  Bad Data CRC: 0x8c7eb6a3 != 0x6b8f0a9c
>  ERROR: Checking data crc failed with Invalid argument
>  ERROR: Loading OS image failed with: Invalid argument
>  ERROR: blspec: Booting failed
>  ERROR: Booting entry 'myapp (/mnt/nfs-192.168.1.1-bootentries-000053dc/loader/entries/erlang.conf)
>  ' failed
>  Nothing bootable found

The nfs share is correctly configured with v3,udp.

**It should be noted that the instructions [2.2 NFS SUPPORT]( https://www.barebox.org/doc/latest/filesystems/nfs.html) are incorrect, a search of the code suggests `linux.rootnfsopts` rather than `global.linux.rootnfsopts` should be set, which functions correctly:**

devinfo nfs0

> Driver: nfs
> Bus: fs
> Parameters:
>   linux.bootargs: root=/dev/nfs nfsroot=192.168.1.1:tmp/grisp,v3,udp ip=dhcp (type: string)
> 

If I run uimage -v on the image referred to in .../loader/entries/erlang.conf I get a different result each time.

> uimage -v beam.zImage
> verifying data CRC... Bad Data CRC: 0x56474aa2 != 0x6b8f0a9c

> uimage -v beam.zImage
> verifying data CRC... Bad Data CRC: 0xb715ff38 != 0x6b8f0a9c

> uimage -v beam.zImage
> verifying data CRC... Bad Data CRC: 0x32ef3817 != 0x6b8f0a9c

> uimage -v beam.zImage
> verifying data CRC... Bad Data CRC: 0x4f2f6424 != 0x6b8f0a9c
> 
 
Note that the CRC in the image is the same, but the  generated value differs each time it's called.

However, if I crc32 the image directly I get the same result each time:

> crc32 -f beam.zImage
> CRC32 for beam.zImage 0x00000000 ... 0x003b9e9e ==> 0x7d66df14

> crc32 -f beam.zImage
> CRC32 for beam.zImage 0x00000000 ... 0x003b9e9e ==> 0x7d66df14

> crc32 -f beam.zImage
> CRC32 for beam.zImage 0x00000000 ... 0x003b9e9e ==> 0x7d66df14
 
So this suggests that it's not udp at fault,  However, If I copy the image to the SD card and run uimage -v the validation is successful...

**Comment by a3f** [comment]
> barebox 2022.02.0-bsp-yocto-i.mx6ul-pd19.1.1 https://github.com/barebox/barebox/pull/1 Fri Sep 1 14:00:23 UTC 2023

This is > 2.5 years old. Have you reproduced this issue with an up-to-date barebox release?

> It should be noted that the instructions [2.2 NFS SUPPORT](https://www.barebox.org/doc/latest/filesystems/nfs.html) are incorrect, a search of the code suggests linux.rootnfsopts rather than global.linux.rootnfsopts should be set, which functions correctly:

The parameter is added with `globalvar_add_simple_string`, that's why there's no `global.` in the code. To access it from the shell, you need the `global.` prefix though.

> If I run uimage -v on the image referred to in .../loader/entries/erlang.conf I get a different result each time.

So over NFS, you get different results each time?

> However, if I crc32 the image directly I get the same result each time:

With directly, you mean you copied it to SD card or to ramfs and then ran the check?

> So this suggests that it's not udp at fault

I don't follow how you arrive at this conclusion.

**Comment by Rashidwi** [comment]
I'm not sure about updating barebox in the [grisp2 bootloader](https://github.com/grisp/grisp2-rtems-toolchain) I've posed the question and will wait and see if it poses problems. 

If I uimage -v across nfs I get a bad crc, 
If I uimage -v across tftp it works. 
If I first copy the file using nfs it works: so udp/nfs appears fine, why then would the crc error only appear when running across nfs?

Would it be possible to test this version and validate it is working correctly? Does the current version work correctly?

Thanks

**Comment by a3f** [comment]
> I'm not sure about updating barebox in the [grisp2 bootloader](https://github.com/grisp/grisp2-rtems-toolchain) I've posed the question and will wait and see if it poses problems.

When issues are reported against upstream, we generally want to see the issue reproduced with the upstream version, so we are sure you didn't run into bugs that were already fixed or are specific to downstream changes.

> If I uimage -v across nfs I get a bad crc,
> If I uimage -v across tftp it works.
> If I first copy the file using nfs it works: so udp/nfs appears fine, why then would the crc error only appear when running across nfs?

Ok, to summarize `uimage -v /mnt/nfs/uImage` is broken. This wasn't clear to me from the shortened commands reported.

> Would it be possible to test this version and validate it is working correctly? Does the current version work correctly?

I reproduced this problem with master; verifying a uImage on file systems that can yield short reads like NFS was indeed broken.

A fix has been submitted to the mailing list here: https://lore.kernel.org/barebox/20241002160714.2423842-1-a.fatoum@pengutronix.de/T/#u

It will probably be part of v2024.10.0 when that's released this month. You can backport the patch of course if you don't want to wait.

Thanks for your report.

P.S: uImage is a legacy image format and you may want to switch to a modern alternative such as [BootloaderSpec files](https://www.barebox.org/doc/latest/user/booting-linux.html#boot-loader-specification) or [FIT images](https://www.thegoodpenguin.co.uk/blog/u-boot-fit-image-overview/).

**Comment by a3f** [comment]
Looking into the code, there are some other potential issues as well. So here's one more patch: https://lore.kernel.org/barebox/20241002163621.2458659-1-a.fatoum@pengutronix.de/T/#u
