### ISSUE TITLE
acpi.h : Necessary header file not included

### ISSUE THREAD

**Issue by healytpk** [barebox/barebox#7]
"acpi.h" can cause a build failure because it doesn't include the necessary header file for "memcmp".

I'm not sure if this is by design (i.e. I'm not sure if you are supposed to include "common.h" before all other headers).

**Comment by a3f** [comment]
Hello @healytpk,

Discussions and patches about the project are usually done on the mailing list: [https://lists.infradead.org/mailman/listinfo/barebox](https://lists.infradead.org/mailman/listinfo/barebox).

To answer you question, headers are preferably self-contained, so yes, I forgot a `#include <linux/string.h>` when I added the file. Would you like to send a patch to the mailing list? :-)

Cheers,
