### ISSUE TITLE
board

### ISSUE THREAD

**Issue by Power535** [barebox/barebox#8]
Hi
Possible adding 7241 usff ?
https://github.com/Broadcom/stblinux-4.1/blob/master/linux/arch/mips/boot/dts/brcm/bcm97241usff.dts
This as 7429

**Comment by olerem** [comment]
Do you mean, to add this chip or board support?
If yes, the answer is: yes, it is possible.
The question is, who will do it?

**Comment by Power535** [comment]
Board 7241
Example
barebox/dts/src/mips/brcm
I need help adding
Who can add ?

**Comment by olerem** [comment]
Your example is only device tree. It is not enough for a bootloader. More work is needed, especially if it is not supported chip. The amount of time to make this work done is in quantity of weeks.
If you can't do it by your self, contact some company who can do it for you or your company. For example you can contract https://www.pengutronix.de/en/index.html

**Comment by Power535** [comment]
How compile for dts ?
barebox/dts/src/mips/brcm
Example 7435

**Comment by olerem** [comment]
To compile a dts:
dtc -I dts -O dtb -o devicetree_file_name.dtb devicetree_file_name.dts

to compile a barebox:
https://barebox.org/doc/latest/user/barebox.html

**Comment by Power535** [comment]
Example
make qemu-malta_defconfig
only need for
barebox/dts/src/mips/brcm

**Comment by olerem** [comment]
i do not understand the question

**Comment by olerem** [comment]
please do not re-edit your questions, comments. It makes  the conversation look absurd.

All supported defconfigs can be found in:
arch/mips/configs

**Comment by Power535** [comment]
No config in folder
arch/mips/configs for  dts/src/mips/brcm
Right ?
I do not understand why then dts

**Comment by olerem** [comment]
The dts files in barebox/dts/ are automatically imported from kernel (all of them). This is done to reduce code duplication between barebox and linux. Devicetrees which are actually used in barebox are in arch/mips/dts

**Comment by Power535** [comment]
Means barebox not support any platform brcm

**Comment by olerem** [comment]
means, barebox support only bcm47xx
